blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/hg-pyun/typescript-performance-analyzer/discussions
    about: Ask questions and discuss with the community
